# Generated by Django 4.1.4 on 2023-01-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
