# Generated by Django 4.1.4 on 2023-01-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_recipe_ingredient_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='recipe_id',
        ),
    ]
